#!/usr/bin/env bash

packages=(
  .
  packages/{{projectHid}}-types
  packages/{{projectHid}}-cms
  packages/{{projectHid}}-ui
  packages/{{projectHid}}-app
)

for i in "${packages[@]}"
do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L {{projectHid}} attach
